language: node_js

node_js:
  - 'node'

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
  - npm install

# Init GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run test

cache:
  directories:
     - ./node_modules

notifications:
  email: false

before_deploy:
  - npm run build
  - pip install --user awscli
  - aws ecr get-login --no-include-email --region us-west-2

deploy:
  provider: script
  script: aws s3 cp /dist/ s3://mapmiptest.webiks.com/ --recursive
  skip_cleanup: true
  on:
    branch: master
