language: node_js

node_js:
  - 'node'

install:
  - npm install

cache:
  directories:
     - ./node_modules

deploy:
  provider: script
  script: "npm run deploy"
  skip_cleanup: true
  on:
    branch: master



notifications:
  email: false
