language: node_js

node_js:
  - 'node'

#before_install:
#  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

#install:
#  - npm install

# Init GUI
#before_script:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

 script:
   - echo "Hi"
#   - npm run build
#
#cache:
#  directories:
#     - ./node_modules

notifications:
  email: false

before_deploy:
  - rm -r dist
  - mkdir dist
  - echo "test" > dist/index.html

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: mapmiptest.webiks.com
  skip_cleanup: true
  local_dir: dist
  region: $AWS_S3_BUCKET_REGION
  on:
    branch: travis-ci-s3-test
